trigger:
- main

pool:
  name: Default

variables:
  - group: terraform-variables

stages:
- stage: Validate
  displayName: 'Validate Terraform'
  jobs:
  - job: Validate
    steps:
    - script: terraform init -backend=false
      displayName: 'Terraform Init'
      workingDirectory: \
    - script: terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: \

- stage: Plan
  displayName: 'Plan Terraform'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - job: Plan
    steps:
    - script: terraform init -backend-config="resource_group_name=rg-terraform-enterprise" -backend-config="storage_account_name=tfstatepriyanka" -backend-config="container_name=tfstate" -backend-config="key=terraform.tfstate"
      displayName: 'Terraform Init'
      workingDirectory: \
      env:
        ARM_SUBSCRIPTION_ID: c967d50f-7f21-4985-bd4f-1befa0e42d1a
        ARM_TENANT_ID: 068b196a-2d57-407f-a70d-3c0571c3266a
        ARM_USE_CLI: "true"
        TF_VAR_admin_password: \$(admin_password)
    - script: terraform plan -out=tfplan
      displayName: 'Terraform Plan'
      workingDirectory: \
      env:
        ARM_SUBSCRIPTION_ID: c967d50f-7f21-4985-bd4f-1befa0e42d1a
        ARM_TENANT_ID: 068b196a-2d57-407f-a70d-3c0571c3266a
        ARM_USE_CLI: "true"
        TF_VAR_admin_password: \$(admin_password)

- stage: Apply
  displayName: 'Apply Terraform'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - job: Apply
    steps:
    - script: terraform init -backend-config="resource_group_name=rg-terraform-enterprise" -backend-config="storage_account_name=tfstatepriyanka" -backend-config="container_name=tfstate" -backend-config="key=terraform.tfstate"
      displayName: 'Terraform Init'
      workingDirectory: \
      env:
        ARM_SUBSCRIPTION_ID: c967d50f-7f21-4985-bd4f-1befa0e42d1a
        ARM_TENANT_ID: 068b196a-2d57-407f-a70d-3c0571c3266a
        ARM_USE_CLI: "true"
        TF_VAR_admin_password: \$(admin_password)
    - script: terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
      workingDirectory: \
      env:
        ARM_SUBSCRIPTION_ID: c967d50f-7f21-4985-bd4f-1befa0e42d1a
        ARM_TENANT_ID: 068b196a-2d57-407f-a70d-3c0571c3266a
        ARM_USE_CLI: "true"
        TF_VAR_admin_password: \$(admin_password)
